### ISSUE TITLE
more money more problems ?

### ISSUE THREAD

**Issue by flutter-painter** [jogboms/money.dart#1]
Hi,

Any reason  for not using https://github.com/onepub-dev/money.dart ?

**Comment by jogboms** [comment]
Hey @flutter-painter 

I actually don't use it cause it does a bit too much plus i use a large integer by default for representing money on the backend. 

I also intentionally will not publish this  to pub.dev as this is a personal utility.

**Comment by flutter-painter** [comment]
ok, pardon my inquisitive tone, was curious since scrutinizing it atm
thx
